"""
data.py -- Media database and training data for CineBot.
Add, remove, or edit entries here without touching the main chatbot code.
"""

GENRE_MAP = {
    "horror": ["horror"], "scary": ["horror"], "creepy": ["horror"],
    "comedy": ["comedy"], "funny": ["comedy"], "hilarious": ["comedy"], "laugh": ["comedy"],
    "action": ["action"],
    "thriller": ["thriller"], "suspense": ["thriller"],
    "drama": ["drama"], "emotional": ["drama"], "moving": ["drama"],
    "romance": ["romance"], "romantic": ["romance"], "love": ["romance"],
    "sci-fi": ["sci-fi"], "scifi": ["sci-fi"], "space": ["sci-fi"],
    "documentary": ["documentary"],
    "animation": ["animation"], "anime": ["animation"], "cartoon": ["animation"],
    "adventure": ["adventure"],
    "fantasy": ["fantasy"],
    "mystery": ["mystery"],
    "dark": ["thriller", "drama"],
}

MEDIA = [
    {"title": "The Grand Budapest Hotel",
     "genres": ["comedy", "adventure"], "decade": "2010s", "type": "movie",
     "description": "A legendary concierge at a famous European hotel bonds with a lobby boy as they get swept up in a plot involving a stolen Renaissance painting."},
    {"title": "Superbad",
     "genres": ["comedy"], "decade": "2000s", "type": "movie",
     "description": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry."},
    {"title": "Knives Out",
     "genres": ["comedy", "mystery", "thriller"], "decade": "2010s", "type": "movie",
     "description": "A quirky, renowned detective investigates the death of the patriarch of an eccentric, combative family."},
    {"title": "What We Do in the Shadows",
     "genres": ["comedy", "horror"], "decade": "2010s", "type": "movie",
     "description": "A hilarious documentary-style look into the daily (or rather, nightly) lives of four vampire roommates sharing a flat."},
    {"title": "Parks and Recreation",
     "genres": ["comedy"], "decade": "2010s", "type": "tv",
     "description": "A dedicated but quirky mid-level bureaucrat in an Indiana Parks department tirelessly strives to make her town a better place."},
    {"title": "Schitt's Creek",
     "genres": ["comedy"], "decade": "2010s", "type": "tv",
     "description": "A wealthy family loses their fortune and is forced to move to a small, rural town they once bought as a joke."},
    {"title": "Fleabag",
     "genres": ["comedy", "drama"], "decade": "2010s", "type": "tv",
     "description": "A dry-witted, grief-riddled young woman navigates life and love in London while rejecting anyone who tries to help her."},
    {"title": "Get Out",
     "genres": ["horror", "thriller"], "decade": "2010s", "type": "movie",
     "description": "A young Black man uncovers a disturbing secret when he visits his white girlfriend's family estate."},
    {"title": "Hereditary",
     "genres": ["horror"], "decade": "2010s", "type": "movie",
     "description": "After the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences that unravel dark secrets about their ancestry."},
    {"title": "A Quiet Place",
     "genres": ["horror", "thriller"], "decade": "2010s", "type": "movie",
     "description": "A family struggles for survival in a post-apocalyptic world where they must live in silence to hide from monsters with ultra-sensitive hearing."},
    {"title": "The Shining",
     "genres": ["horror", "thriller"], "decade": "1980s", "type": "movie",
     "description": "A family heads to an isolated hotel for the winter where a sinister presence drives the father into violence."},
    {"title": "Stranger Things",
     "genres": ["horror", "sci-fi", "thriller"], "decade": "2010s", "type": "tv",
     "description": "A group of kids in the 1980s uncover a secret government plot and supernatural forces when their friend goes missing."},
    {"title": "Midsommar",
     "genres": ["horror"], "decade": "2010s", "type": "movie",
     "description": "A grieving young woman travels to a secluded Swedish festival that rapidly devolves into a bizarre and violent cult ritual."},
    {"title": "Die Hard",
     "genres": ["action", "thriller"], "decade": "1980s", "type": "movie",
     "description": "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party in a Los Angeles skyscraper."},
    {"title": "Mad Max: Fury Road",
     "genres": ["action", "sci-fi"], "decade": "2010s", "type": "movie",
     "description": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners and a drifter named Max."},
    {"title": "The Dark Knight",
     "genres": ["action", "thriller"], "decade": "2000s", "type": "movie",
     "description": "Batman faces his greatest psychological and physical test as he battles the Joker, a criminal mastermind determined to plunge Gotham City into anarchy."},
    {"title": "John Wick",
     "genres": ["action", "thriller"], "decade": "2010s", "type": "movie",
     "description": "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him."},
    {"title": "Speed",
     "genres": ["action", "thriller"], "decade": "1990s", "type": "movie",
     "description": "A police officer must rescue hostages on a city bus rigged with a bomb programmed to explode if the bus slows down below 50 mph."},
    {"title": "Kill Bill",
     "genres": ["action", "thriller"], "decade": "2000s", "type": "movie",
     "description": "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her."},
    {"title": "Inception",
     "genres": ["sci-fi", "thriller"], "decade": "2010s", "type": "movie",
     "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O."},
    {"title": "Interstellar",
     "genres": ["sci-fi", "drama"], "decade": "2010s", "type": "movie",
     "description": "A team of explorers travel through a newly discovered wormhole in space in a desperate attempt to ensure humanity's survival."},
    {"title": "The Matrix",
     "genres": ["sci-fi", "action"], "decade": "1990s", "type": "movie",
     "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers."},
    {"title": "Black Mirror",
     "genres": ["sci-fi", "thriller"], "decade": "2010s", "type": "tv",
     "description": "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide."},
    {"title": "Severance",
     "genres": ["sci-fi", "thriller", "drama"], "decade": "2020s", "type": "tv",
     "description": "Employees at a mysterious company have their memories surgically divided between their work and personal lives, leading to a thrilling discovery."},
    {"title": "Arrival",
     "genres": ["sci-fi", "drama"], "decade": "2010s", "type": "movie",
     "description": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft touch down across the globe."},
    {"title": "The Shawshank Redemption",
     "genres": ["drama"], "decade": "1990s", "type": "movie",
     "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."},
    {"title": "Parasite",
     "genres": ["drama", "thriller"], "decade": "2010s", "type": "movie",
     "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan."},
     {"title": "Five Nights at Freddy's",
     "genres": ["horror", "thriller", "mystery"], "decade": "2020s", "type": "movie",
     "description": "A troubled security guard begins a night shift at an abandoned family entertainment center, only to discover the animatronic mascots are possessed and deadly."},
    {"title": "Everything Everywhere All at Once",
     "genres": ["sci-fi", "action", "comedy"], "decade": "2020s", "type": "movie",
     "description": "A middle-aged Chinese immigrant is swept up in an insane adventure where she must save the multiverse by connecting with alternate versions of herself."},
    {"title": "Breaking Bad",
     "genres": ["drama", "thriller"], "decade": "2000s", "type": "tv",
     "description": "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family's future."},
    {"title": "Succession",
     "genres": ["drama", "comedy"], "decade": "2010s", "type": "tv",
     "description": "The Roy family is known for controlling the biggest media and entertainment company in the world, but their dynamic changes when their father considers stepping down."},
    {"title": "The Bear",
     "genres": ["drama", "comedy"], "decade": "2020s", "type": "tv",
     "description": "A young, classically trained chef returns to Chicago to run his chaotic family sandwich shop after a heartbreaking death."},
    {"title": "Pride and Prejudice",
     "genres": ["romance", "drama"], "decade": "2000s", "type": "movie",
     "description": "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy, who reluctantly finds himself falling in love with a woman beneath his class."},
    {"title": "About Time",
     "genres": ["romance", "drama", "comedy"], "decade": "2010s", "type": "movie",
     "description": "At the age of 21, Tim discovers he can travel in time and decides to use his ability to improve his life by getting a girlfriend."},
    {"title": "Normal People",
     "genres": ["romance", "drama"], "decade": "2020s", "type": "tv",
     "description": "Follows the tender but complicated relationship of Marianne and Connell from the end of their school days in a small-town Ireland to their undergraduate years."},
    {"title": "Spider-Man: Into the Spider-Verse",
     "genres": ["animation", "action", "adventure"], "decade": "2010s", "type": "movie",
     "description": "Teenager Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat to all realities."},
    {"title": "Spirited Away",
     "genres": ["animation", "adventure", "fantasy"], "decade": "2000s", "type": "movie",
     "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts."},
    {"title": "BoJack Horseman",
     "genres": ["animation", "comedy", "drama"], "decade": "2010s", "type": "tv",
     "description": "A washed-up, depressed, anthropomorphic horse who was the star of a 90s sitcom tries to figure out what to do with his life."},
    {"title": "Planet Earth II",
     "genres": ["documentary"], "decade": "2010s", "type": "tv",
     "description": "An immersive documentary series that explores the stunning and diverse natural habitats and wildlife of our planet."},
    {"title": "13th",
     "genres": ["documentary"], "decade": "2010s", "type": "movie",
     "description": "An in-depth look at the prison system in the United States and how it reveals the nation's history of racial inequality."},
    {"title": "Free Solo",
     "genres": ["documentary", "adventure"], "decade": "2010s", "type": "movie",
     "description": "A stunning documentary following free soloist climber Alex Honnold as he prepares to achieve his lifelong dream: climbing the face of El Capitan without a rope."},
]

INTENT_TEXTS = [
    # recommend
    "I want something funny", "suggest me a good film", "what should I watch tonight",
    "I'm in the mood for a thriller", "can you recommend a sci-fi show",
    "give me a movie recommendation", "I feel like watching something scary",
    "what's a good 90s film", "recommend me something to binge",
    "I'd like a romantic movie please",
    "horror", "comedy", "action", "romance", "drama", "thriller",
    "sci-fi", "documentary", "animation", "adventure", "mystery", "fantasy",
    "something horror", "something romantic", "something funny", "something scary",
    "a horror film", "a comedy film", "an action movie", "a romantic film",
    # more
    "show me another one", "give me more options", "something else please",
    "not that one, another", "can I get another suggestion", "more recommendations",
    "what else have you got", "try again", "I've seen that, give me another", "next one please",
    # farewell
    "bye", "goodbye", "that's all thanks", "I'm done", "quit",
    "exit", "thanks, see you", "I'll stop here", "cheers, bye", "I'm going now",
    # frustrated
    "that's useless", "you're not helping", "terrible suggestions", "this is rubbish",
    "I hate this chatbot", "you're awful", "stop giving me bad recommendations",
    "this is pointless", "what a waste of time", "none of these are good",
    # positive feedback
    "great recommendation", "I love that film", "that sounds perfect", "brilliant suggestion",
    "yes that's exactly what I wanted", "nice one thanks", "that's a good pick",
    "I really enjoyed that", "perfect thanks", "that was a great choice",
]

INTENT_LABELS = [0]*30 + [1]*10 + [2]*10 + [3]*10 + [4]*10
INTENT_NAMES  = {0: "recommend", 1: "more", 2: "farewell", 3: "frustrated", 4: "positive_feedback"}